### PR TITLE
Fix not compiling code when AA is running first

### PR DESCRIPTION
**Pull request by WonderCsabo**
It is possible that the AA processor is running first, then the
PermissionDispatcher processor. In that case, AA claims the @RuntimePermissions annotation,
so the latter processor cannot generate the permission handling helper class.

This commit removes the @RuntimePermissions handler from this plugin,
so it always can be claimed by PermissionDispatcher, regardless of processor order.

#7

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@AleksanderMielczarek @dodgex this has the side effect for generating the helper class for the AA generated subclass as well. :( I have no better idea.

You can test this by explicitly setting the processor classes (and order):
```groovy
android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                classNames = ["org.androidannotations.internal.AndroidAnnotationProcessor", "permissions.dispatcher.processor.PermissionsProcessor"]
            }
        }
    }
}
```

**Comment by AleksanderMielczarek** [comment]
@WonderCsabo thank you for contribution 😃 I agree that duplicate `PermisionsHandler` is not a perfect solution. But as long as one is using AA with PD together it's really hidden. And finally the unused one can be removed by ProGuard so in my opinion it's not a big deal.

I also wonder if is it possible to prevent AA for rewriting `@RuntimePermissions` in generated class? If not maybe it will be a good idea to expand plugins with such functionality.

**Comment by WonderCsabo** [comment]
I am thinking about not copying annotations to generated classes at all - I see more downsides than benefits right now. 

However, this change is needed regardless, AA cannot consume @RuntimePermission.

**Comment by WonderCsabo** [comment]
@AleksanderMielczarek i would be really happy for another release, if you find this acceptable. :)

**Comment by AleksanderMielczarek** [comment]
Merged. New release will appear soon 😃

**Comment by WonderCsabo** [comment]
Thanks!

**Pull request merged**
