### PR TITLE
Override methods to delegate

### PR DESCRIPTION
**Pull request by WonderCsabo**
#5

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Also summoning @smaugho and @dodgex to check this. :)

**Comment by smaugho** [comment]
@WonderCsabo it is working very well :).. thanks for it!.. 

I just don't understand very well why it is needed having the variable `permissionDispatcherCalled_`
Typically when the permission dialog is called, the application is blocked in background.. Maybe the idea is to handle the case of multiple calls, which could be done asynchronously... not sure, but if this is the case, not sure why in the case of this variable being true (this would mean there's a call is progress), then why is the super method called:

```java
       if (!permissionDispatcherCalled_) {
            permissionDispatcherCalled_ = true;
            MainActivityPermissionsDispatcher.askForPermissionWithCheck(this);
        } else {
            permissionDispatcherCalled_ = false;
            MainActivity_.super.askForPermission();
        }
```

As I said above, maybe I simply didn't understand the importance of having the field... but well, let's say this method could be called asynchronously (from a different thread), doesn't this means that a second call to the method will call the super method itself, without caring if the permission was granted or not?. 

Well, just as suggestions, would be good to have the references to `JExpr._this()` or other included statically, similar to how is done most of the time in AndroidAnnotations. Also, in the line, 38 of the NeedsPermissionHandler, it is used `AbstractJClass delegateClass = getCodeModel().ref(delegateClassName);`, also just to keep it clearer, could we replace it maybe by `AbstractJClass delegateClass = getJClass(delegateClassName);` 

These are just suggestion and doesn't represent any change for the behavior itself.

**Comment by dodgex** [comment]
Unfortunately I have no idea how permission dispatcher works or how the permissions have to be requested with the runtime permissions api as currently none of my projects actually need any permissions that need to be requested.

I havent seen any flaws when (quickly) reading over the commit, and due to the mentioned reason i can't review the technical changes.

**Comment by WonderCsabo** [comment]
@smaugho that field is needed to avoid infinite recursion. :) 

Without that field the following method call chain would happen:
```jav
activity.onClick() -> activity.showCamera()
activity.showCamera() -> subclass.showCamera()
subclass.showCamera() -> delegate.showCamera()
delegate.showCamera() -> activity.showCamera()
```
And in that point these calls would go on infinitely.

Thanks for the suggestions, i will update the PR.

@dodgex thanks for looking into it anyway!

**Comment by hotchemi** [comment]
👀

**Comment by smaugho** [comment]
Working like a charm!, @AleksanderMielczarek, looking forward to have this PR into your project, really nice plugin for AndroidAnnotation! 

@hotchemi thanks as well, PermissionsDispatcher it is really cool...

**Comment by AleksanderMielczarek** [comment]
@WonderCsabo thanks for this improvement. Now it will be finally working like it should from the very beginning 😃 

@smaugho I always do such thing on main thread to avoid problems.

As I don't know neither AA nor PermissionDispatcher API, I will pass on your experience @WonderCsabo, @dodgex, @hotchemi. Just tell me if I can merge this and new release will appear immediately.

**Comment by WonderCsabo** [comment]
@AleksanderMielczarek thanks for the release and for the positive feedback! I think this plugin is a great example why we created the plugin system for AndroidAnnotations.

**Pull request merged**
